# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Patricia Sauthoff
tagline:          'A website'
description:      'journalist, academic, cyclist, coffee/beer/music/art snob, @mediagazer editor, @soas phd student'
url:              http://patriciasauthoff.com

author:
  name:           'Patricia Sauthoff'
  url:            https://twitter.com/gitagovinda

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/coreyp/hyde